import { useState } from 'react'
import { Button, Card, Form, Input, Segmented, Typography, message } from 'antd'
import { LockOutlined, UserOutlined } from '@ant-design/icons'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useTheme } from '../../constants/theme'
import { useAuth } from '../../auth/AuthProvider'

type Mode = 'login' | 'register'
type FormValues = { username: string; password: string; display_name?: string }

export default function LoginPage() {
  const { user, login, register } = useAuth(); const { theme } = useTheme(); const navigate = useNavigate(); const location = useLocation()
  const [mode, setMode] = useState<Mode>('login'); const [submitting, setSubmitting] = useState(false); const [form] = Form.useForm<FormValues>()
  if (user) return <Navigate to="/" replace />
  const destination = (location.state as { from?: { pathname?: string; search?: string } } | null)?.from
  const complete = async (values: FormValues) => { setSubmitting(true); try { if (mode === 'register') await register(values); else await login(values); navigate(`${destination?.pathname || '/'}${destination?.search || ''}`, { replace: true }) } catch (error) { message.error(error instanceof Error ? error.message : '登录失败') } finally { setSubmitting(false) } }
  return <main className="yl-login" style={{ '--login-bg': theme.bgPage } as React.CSSProperties}>
    <div className="yl-login__scene" aria-hidden="true" /><div className="yl-login__wash" aria-hidden="true" />
    <div className="yl-login__content"><section className="yl-login__intro"><div className="yl-login__eyebrow"><span className="yl-login__dot" /> CREATIVE PRODUCTION DESK</div><Typography.Title level={1} className="yl-login__title">YL Craft</Typography.Title><Typography.Paragraph className="yl-login__subtitle">把灵感整理成可继续推进的作品。</Typography.Paragraph><div className="yl-login__meta"><span>故事</span><i /><span>分镜</span><i /><span>素材</span><i /><span>生成</span></div></section>
      <section className="yl-login__panel"><div className="yl-login__panel-head"><Typography.Title level={3} style={{ color: theme.textPrimary, margin: 0 }}>{mode === 'login' ? '欢迎回来' : '建立工作空间'}</Typography.Title><Typography.Paragraph style={{ color: theme.textSecondary, margin: '6px 0 0' }}>{mode === 'login' ? '登录后继续你的创作流程' : '创建一个本地账号，保存你的项目进度'}</Typography.Paragraph></div><Card bordered style={{ borderColor: theme.border, background: theme.bgCard, boxShadow: theme.shadowElevated }}><Segmented<Mode> block value={mode} options={[{ label: '登录', value: 'login' }, { label: '注册', value: 'register' }]} onChange={(next) => { setMode(next); form.resetFields() }} style={{ marginBottom: 20 }} /><Form form={form} layout="vertical" requiredMark={false} onFinish={complete}>{mode === 'register' && <Form.Item name="display_name" label="显示名称"><Input maxLength={120} placeholder="可选" /></Form.Item>}<Form.Item name="username" label="用户名" rules={[{ required: true, message: '请输入用户名' }, { pattern: /^[A-Za-z0-9_.-]{3,64}$/, message: '使用 3-64 位字母、数字、点、下划线或连字符' }]}><Input prefix={<UserOutlined />} autoComplete="username" /></Form.Item><Form.Item name="password" label="密码" rules={[{ required: true, message: '请输入密码' }, { min: 8, message: '密码至少需要 8 个字符' }]}><Input.Password prefix={<LockOutlined />} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></Form.Item><Button type="primary" htmlType="submit" loading={submitting} block>{mode === 'login' ? '登录' : '创建账号'}</Button></Form></Card><div className="yl-login__foot">本地部署 · 数据留在你的工作台</div></section></div>
    <style>{`.yl-login{min-height:100vh;position:relative;overflow:hidden;background:${theme.bgPage};color:${theme.textPrimary}}.yl-login__scene{position:absolute;inset:0;background:url('/login/studio-background.png') center/cover no-repeat;transform:scale(1.02)}.yl-login__wash{position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,12,17,.98) 0%,rgba(7,12,17,.86) 30%,rgba(7,12,17,.42) 64%,rgba(7,12,17,.7) 100%)}.yl-login__content{position:relative;z-index:1;min-height:100vh;max-width:1240px;margin:0 auto;padding:56px 48px;display:grid;grid-template-columns:minmax(280px,1fr) minmax(340px,420px);align-items:center;gap:64px}.yl-login__intro{padding:28px 0}.yl-login__eyebrow{color:${theme.primary};font:600 11px/1.4 Inter,sans-serif;letter-spacing:.16em}.yl-login__dot{display:inline-block;width:7px;height:7px;margin-right:9px;border-radius:50%;background:${theme.primary};box-shadow:0 0 0 5px ${theme.primaryAlpha(.14)};vertical-align:1px}.yl-login__title{color:${theme.textPrimary}!important;font-size:clamp(48px,7vw,88px)!important;line-height:.98!important;letter-spacing:-.04em;margin:22px 0 18px!important}.yl-login__subtitle{color:${theme.textSecondary}!important;font-size:18px;max-width:330px;margin:0!important}.yl-login__meta{display:flex;align-items:center;gap:13px;margin-top:36px;color:${theme.textSecondary};font-size:12px}.yl-login__meta i{width:3px;height:3px;border-radius:50%;background:${theme.primary};opacity:.7}.yl-login__panel{width:100%}.yl-login__panel-head{margin-bottom:18px}.yl-login__panel .ant-card{border-radius:8px}.yl-login__panel .ant-segmented{background:${theme.bgInput}}.yl-login__panel .ant-form-item-label>label{color:${theme.textSecondary}}.yl-login__panel .ant-input-affix-wrapper,.yl-login__panel .ant-input{min-height:42px}.yl-login__panel .ant-btn{min-height:44px;font-weight:600}.yl-login__foot{color:${theme.textSecondary};opacity:.72;font-size:12px;text-align:center;margin-top:16px}@media(max-width:760px){.yl-login__wash{background:linear-gradient(180deg,rgba(7,12,17,.73) 0%,rgba(7,12,17,.94) 55%,rgba(7,12,17,.99) 100%)}.yl-login__content{grid-template-columns:1fr;gap:30px;padding:34px 20px 24px;align-content:center}.yl-login__intro{padding:0}.yl-login__title{font-size:clamp(46px,15vw,68px)!important;margin-top:18px!important}.yl-login__subtitle{font-size:16px}.yl-login__meta{margin-top:22px}.yl-login__panel-head{margin-bottom:14px}}`}</style></main>
}
