import { Alert, Badge, Button, Card, Checkbox, Collapse, Empty, Form, Image, Input, InputNumber, List, Modal, Popconfirm, Progress, Segmented, Select, Skeleton, Space, Table, Tabs, Tag, Tooltip, Typography, message } from 'antd'
import { BranchesOutlined, CheckCircleOutlined, CloudUploadOutlined, CopyOutlined, DeleteOutlined, DeploymentUnitOutlined, DownOutlined, DownloadOutlined, EditOutlined, EnvironmentOutlined, ExclamationCircleOutlined, EyeOutlined, FileTextOutlined, FolderAddOutlined, FolderOpenOutlined, HistoryOutlined, MenuFoldOutlined, MenuUnfoldOutlined, PictureOutlined, PlusOutlined, ReloadOutlined, RobotOutlined, ThunderboltOutlined, UserOutlined, VideoCameraOutlined } from '@ant-design/icons'
import { agentChat, createCreativeProject, createCreativeProjectFromNovel, deleteCreativeProject, extractCreativeProjectContinuity, getCreativeProjectContinuityContextSummary, getCreativeProjectNarrativeContextPreview, getCreativeProjectNarrativeGraph, getCreativeProjectNarrativeHealth, getCreativeProjectWritingPreflight, listCreativeProjectNarrativeRuns, controlCreativeProjectNarrativeRun, configureCreativeProjectNarrativeAutopilot, generateCharacterPortrait, generateCreativeProjectChapterPlan, generateCreativeProjectChapterOutline, generateCreativeProjectNovelBody, generateCreativeProjectOutline, extractCreativeProjectCharacters, generateCreativeProjectScript, generateCreativeProjectStoryboard, generateImage as generateImageApi, getAsset, getCharacter, getCreativeProjectCanvas, getImageTask, getImageBackends, getPlatformTemplates, listAssets, linkCreativeProjectAsset, listConnectors, listCreativeProjectContents, listCreativeProjectContinuityCandidates, listCreativeProjectForeshadowing, listCreativeProjectAssets, listCreativeProjectGenerationLogs, listCreativeProjects, getOrCreatePrevisScene, listTasks, matchCreativeProjectReferenceAssets, promoteCreativeProjectWriterRoomContent, refineCreativeProjectNovelBody, regenerateCreativeProjectChapterOutlineScenes, runCreativeProjectPipeline, runCreativeProjectWriterRoomStep, rewriteCreativeProjectParagraph, resolveCreativeProjectContinuityCandidate, decideCreativeProjectForeshadowing, splitCreativeProjectComicPages, syncCreativeProjectBible, syncCreativeProjectCharacters, saveCreativeProjectCanvas, saveCreativeProjectContentAsAsset, saveCreativeProjectContentPackage, planCreativeProjectContentPackage, getTask, updateCreativeProject, updateCreativeProjectContent, type PlatformTemplate, type CreativeProjectContinuityCandidate } from '../../api'
import { startProjectWorldExtraction, listProjectWorldDomains, listProjectWorldEntities, listProjectWorldEntityRelations, listWorldBuildingSuggestions, confirmSuggestedField, ignoreSuggestedField, upsertProjectWorldDomain, resetProjectWorldDomain, previewEntityExpansion, expandEntityAttributes, expandWorldDomain, draftWorldTemplate, listWorldTemplates, upsertWorldTemplate, deleteWorldTemplate, type WorldBuildingSuggestions, type WorldBuildingTemplate, type WorldDomainExpansionTask, type WorldEntity, type WorldEntityRelation } from '../../api/novelSource'
import type { ChapterPlanItem, ChapterPlan, CreativeProject, CreativeProjectGenerateResponse, CreativeProjectListResponse, CreativeProjectResponse, Provider, StoryOutline, StoryOutlineCharacter, WritingPreflight, WritingMethodCandidate } from '../../types/api'
import { useStoryPageContext } from './hooks/useStoryPageContext'
import { StoryWorkspaceShell } from './components/StoryWorkspaceShell'


export default function StoryPage() {
  const ctx = useStoryPageContext()

  return <StoryWorkspaceShell ctx={ctx} />
}
