"""initial_schema

Revision ID: 2d4ffb118355
Revises: 
Create Date: 2026-07-06 00:01:15.716643
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4ffb118355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('allowed_tools_json', sa.Text(), nullable=True),
    sa.Column('default_context_json', sa.Text(), nullable=True),
    sa.Column('default_project_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('default_workflow', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('default_skill_ids_json', sa.Text(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_default_project_id'), 'agent_profiles', ['default_project_id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_is_builtin'), 'agent_profiles', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_agent_profiles_is_default'), 'agent_profiles', ['is_default'], unique=False)
    op.create_index(op.f('ix_agent_profiles_name'), 'agent_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_agent_profiles_role_type'), 'agent_profiles', ['role_type'], unique=False)
    op.create_index(op.f('ix_agent_profiles_user_id'), 'agent_profiles', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('parent_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_profile_id'), 'agent_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_threads',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('active_profile_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_threads_active_profile_id'), 'agent_threads', ['active_profile_id'], unique=False)
    op.create_index(op.f('ix_agent_threads_status'), 'agent_threads', ['status'], unique=False)
    op.create_index(op.f('ix_agent_threads_user_id'), 'agent_threads', ['user_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_connectors',
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_type', sa.Enum('llm', 'image', 'video', 'tts', 'stt', 'embedding', name='aiprovidertype'), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('available_models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('request_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter_transforms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supported_sizes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_reference_image', sa.Boolean(), nullable=False),
    sa.Column('support_multiple_reference_images', sa.Boolean(), nullable=False),
    sa.Column('reference_image_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_image_array_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('normalize_embeddings', sa.Boolean(), nullable=False),
    sa.Column('support_vision_input', sa.Boolean(), nullable=False),
    sa.Column('test_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('test_timeout', sa.Integer(), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('price_per_call', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('api_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_provider_metadata',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supported_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('available_models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_params', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_templates', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_configs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supported_sizes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_image_configs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_transforms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('ai_usage_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('quota', sa.Float(), nullable=True),
    sa.Column('quota_used', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=False)
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=True)
    op.create_table('asset_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'TEXT', 'MODEL', 'CHARACTER', 'WORLD_SETTING', 'WORKFLOW', 'THREE_D_MODEL', 'ANIMATION', 'SUBTITLE', 'COLLECTION', 'JIANYING_DRAFT', name='assettype'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('phash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_nodes_asset_type'), 'asset_nodes', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_nodes_created_at'), 'asset_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_nodes_name'), 'asset_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_asset_nodes_parent_id'), 'asset_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_asset_nodes_phash'), 'asset_nodes', ['phash'], unique=False)
    op.create_index(op.f('ix_asset_nodes_use_count'), 'asset_nodes', ['use_count'], unique=False)
    op.create_table('book_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_type', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_order', sa.Integer(), nullable=False),
    sa.Column('search_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explore', sa.Boolean(), nullable=False),
    sa.Column('cookie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_ui', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_check_js', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('respond_time', sa.Integer(), nullable=False),
    sa.Column('last_update_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_search', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_book_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_toc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_explore', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ylcraft_rule', sa.Text(), nullable=False),
    sa.Column('original_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_source', sa.Text(), nullable=False),
    sa.Column('migration_log', sa.Text(), nullable=False),
    sa.Column('enabled_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_sources_book_source_name'), 'book_sources', ['book_source_name'], unique=False)
    op.create_index(op.f('ix_book_sources_book_source_url'), 'book_sources', ['book_source_url'], unique=True)
    op.create_index(op.f('ix_book_sources_rule_format'), 'book_sources', ['rule_format'], unique=False)
    op.create_table('character_story_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_identity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_faction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_costume', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_prompt_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ooc_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('off_model_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bible_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_story_links_character_id'), 'character_story_links', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_story_links_local_faction'), 'character_story_links', ['local_faction'], unique=False)
    op.create_index(op.f('ix_character_story_links_local_status'), 'character_story_links', ['local_status'], unique=False)
    op.create_index(op.f('ix_character_story_links_story_id'), 'character_story_links', ['story_id'], unique=False)
    op.create_index(op.f('ix_character_story_links_usage_role'), 'character_story_links', ['usage_role'], unique=False)
    op.create_index(op.f('ix_character_story_links_world_id'), 'character_story_links', ['world_id'], unique=False)
    op.create_index(op.f('ix_character_story_links_world_name'), 'character_story_links', ['world_name'], unique=False)
    op.create_table('characters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('appearance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('costume_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_items', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expressions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('poses', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_consistency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identity_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motivation_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speech_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('behavior_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ability_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arc_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portrait_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portrait_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portrait_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_asset_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_portrait_node_id'), 'characters', ['portrait_node_id'], unique=False)
    op.create_table('comfyui_nodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capabilities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_resolution', sa.Integer(), nullable=False),
    sa.Column('supported_models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('max_queue_size', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('success_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfyui_nodes_name'), 'comfyui_nodes', ['name'], unique=False)
    op.create_table('comfyui_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_type', sa.Enum('TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE', 'INPAINTING', 'UPSCALE', 'CONTROLNET', 'VIDEO', 'CUSTOM', name='workflowcategory'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('negative_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('outputs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_images', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfyui_tasks_prompt_id'), 'comfyui_tasks', ['prompt_id'], unique=True)
    op.create_index(op.f('ix_comfyui_tasks_status'), 'comfyui_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_comfyui_tasks_task_type'), 'comfyui_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_comfyui_tasks_template_id'), 'comfyui_tasks', ['template_id'], unique=False)
    op.create_table('comfyui_workflow_presets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfyui_workflow_presets_name'), 'comfyui_workflow_presets', ['name'], unique=False)
    op.create_index(op.f('ix_comfyui_workflow_presets_template_id'), 'comfyui_workflow_presets', ['template_id'], unique=False)
    op.create_table('comfyui_workflow_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE', 'INPAINTING', 'UPSCALE', 'CONTROLNET', 'VIDEO', 'CUSTOM', name='workflowcategory'), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('node_mapping', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('default_preset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfyui_workflow_templates_category'), 'comfyui_workflow_templates', ['category'], unique=False)
    op.create_index(op.f('ix_comfyui_workflow_templates_name'), 'comfyui_workflow_templates', ['name'], unique=False)
    op.create_table('creative_projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outline_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_projects_created_at'), 'creative_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_creative_projects_current_stage'), 'creative_projects', ['current_stage'], unique=False)
    op.create_index(op.f('ix_creative_projects_project_type'), 'creative_projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_creative_projects_source_type'), 'creative_projects', ['source_type'], unique=False)
    op.create_index(op.f('ix_creative_projects_status'), 'creative_projects', ['status'], unique=False)
    op.create_index(op.f('ix_creative_projects_title'), 'creative_projects', ['title'], unique=False)
    op.create_table('live2d_bones',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('weights', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live2d_bones_model_id'), 'live2d_bones', ['model_id'], unique=False)
    op.create_table('live2d_models',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processing_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('textures_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motions_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live2d_models_name'), 'live2d_models', ['name'], unique=False)
    op.create_table('live2d_motions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motion_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live2d_motions_model_id'), 'live2d_motions', ['model_id'], unique=False)
    op.create_table('novel_chapters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_chapters_asset_id'), 'novel_chapters', ['asset_id'], unique=False)
    op.create_index(op.f('ix_novel_chapters_chapter_index'), 'novel_chapters', ['chapter_index'], unique=False)
    op.create_table('platform_connections',
    sa.Column('platform', sa.Enum('XHS', 'DOUYIN', 'KUAISHOU', 'BILIBILI', 'WEIBO', 'ZHIHU', 'YOUTUBE', 'TIKTOK', 'TWITTER', 'TELEGRAM', 'WECHAT_MP', 'OPENAI', 'ANTHROPIC', 'MINIMAX', 'GOOGLE', 'WEBDAY', 'S3', 'FTP', name='platformtype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sa.Enum('COOKIE', 'API_KEY', 'OAUTH2', 'PASSWORD', 'NONE', name='authtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'FAILED', 'UNKNOWN', name='connectionstatus'), nullable=False),
    sa.Column('credentials', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquisition_method', sa.Enum('MANUAL', 'PLAYWRIGHT', 'QRCODE', name='acquisitionmethod'), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cookie_content', sa.Text(), nullable=True),
    sa.Column('domains', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('test_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('template_scope', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('template_stage', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_template', sa.Text(), server_default='', nullable=False),
    sa.Column('outline_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_size', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_templates_platform'), 'platform_templates', ['platform'], unique=True)
    op.create_index(op.f('ix_platform_templates_template_scope'), 'platform_templates', ['template_scope'], unique=False)
    op.create_index(op.f('ix_platform_templates_template_stage'), 'platform_templates', ['template_stage'], unique=False)
    op.create_table('stories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plot_outline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('music_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('characters_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenes_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_table('story_character_portraits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portrait_urls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_character_portraits_character_name'), 'story_character_portraits', ['character_name'], unique=False)
    op.create_index(op.f('ix_story_character_portraits_story_id'), 'story_character_portraits', ['story_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_asset_count'), 'tags', ['asset_count'], unique=False)
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_level'), 'tags', ['level'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_parent_id'), 'tags', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tags_path'), 'tags', ['path'], unique=False)
    op.create_table('torrent_downloads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('torrent_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('download_speed', sa.BigInteger(), nullable=False),
    sa.Column('upload_speed', sa.BigInteger(), nullable=False),
    sa.Column('downloaded_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('selected_files_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torrent_downloads_engine'), 'torrent_downloads', ['engine'], unique=False)
    op.create_index(op.f('ix_torrent_downloads_status'), 'torrent_downloads', ['status'], unique=False)
    op.create_index(op.f('ix_torrent_downloads_torrent_hash'), 'torrent_downloads', ['torrent_hash'], unique=False)
    op.create_table('vector_docs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_docs_asset_id'), 'vector_docs', ['asset_id'], unique=False)
    op.create_table('vector_indexes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_indexes_name'), 'vector_indexes', ['name'], unique=False)
    op.create_table('wechat_mp_downloads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_fake_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_context_snapshots',
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_context_snapshots_created_at'), 'agent_context_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_context_snapshots_kind'), 'agent_context_snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_agent_context_snapshots_run_id'), 'agent_context_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_context_snapshots_thread_id'), 'agent_context_snapshots', ['thread_id'], unique=False)
    op.create_table('agent_memories',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('message_ids', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_run_id'), 'agent_memories', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_thread_id'), 'agent_memories', ['thread_id'], unique=False)
    op.create_table('agent_memory_snapshots',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('memory_context', sa.Text(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('tool_index_text', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_snapshots_profile_id'), 'agent_memory_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_snapshots_run_id'), 'agent_memory_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_snapshots_session_id'), 'agent_memory_snapshots', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_snapshots_user_id'), 'agent_memory_snapshots', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.create_index(op.f('ix_agent_messages_run_id'), 'agent_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_thread_id'), 'agent_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_tool_call_id'), 'agent_messages', ['tool_call_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('step_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('linked_objects_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_order_index'), 'agent_run_steps', ['order_index'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_profile_id'), 'agent_run_steps', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_run_id'), 'agent_run_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_session_id'), 'agent_run_steps', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_status'), 'agent_run_steps', ['status'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_step_type'), 'agent_run_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_agent_run_steps_tool_name'), 'agent_run_steps', ['tool_name'], unique=False)
    op.create_table('agent_skills',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('skill_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_node_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('civitai_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('civitai_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_words', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_weight', sa.Float(), nullable=False),
    sa.Column('training_resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('preview_urls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['asset_node_id'], ['asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_asset_node_id'), 'ai_models', ['asset_node_id'], unique=False)
    op.create_index(op.f('ix_ai_models_base_model'), 'ai_models', ['base_model'], unique=False)
    op.create_index(op.f('ix_ai_models_civitai_model_id'), 'ai_models', ['civitai_model_id'], unique=False)
    op.create_index(op.f('ix_ai_models_file_hash'), 'ai_models', ['file_hash'], unique=False)
    op.create_index(op.f('ix_ai_models_model_type'), 'ai_models', ['model_type'], unique=False)
    op.create_table('asset_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_node_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_node_id'], ['asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_embeddings_asset_node_id'), 'asset_embeddings', ['asset_node_id'], unique=True)
    op.create_table('asset_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('DERIVED_FROM', 'USES', 'REFERENCES', 'CONTAINS', 'VARIANT_OF', name='relationtype'), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['asset_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_relations_relation_type'), 'asset_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_asset_relations_source_id'), 'asset_relations', ['source_id'], unique=False)
    op.create_index(op.f('ix_asset_relations_target_id'), 'asset_relations', ['target_id'], unique=False)
    op.create_table('asset_tag_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_node_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_node_id'], ['asset_nodes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_tag_links_asset_node_id'), 'asset_tag_links', ['asset_node_id'], unique=False)
    op.create_index(op.f('ix_asset_tag_links_tag_id'), 'asset_tag_links', ['tag_id'], unique=False)
    op.create_table('asset_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_node_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lineage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_node_id'], ['asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_versions_asset_node_id'), 'asset_versions', ['asset_node_id'], unique=False)
    op.create_index(op.f('ix_asset_versions_created_at'), 'asset_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_versions_version_number'), 'asset_versions', ['version_number'], unique=False)
    op.create_table('book_source_cookies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cookie_content', sa.Text(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_source_id'], ['book_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_source_cookies_book_source_id'), 'book_source_cookies', ['book_source_id'], unique=False)
    op.create_index(op.f('ix_book_source_cookies_domain'), 'book_source_cookies', ['domain'], unique=False)
    op.create_index(op.f('ix_book_source_cookies_expires_at'), 'book_source_cookies', ['expires_at'], unique=False)
    op.create_index(op.f('ix_book_source_cookies_is_active'), 'book_source_cookies', ['is_active'], unique=False)
    op.create_table('project_contents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['creative_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_contents_chapter_number'), 'project_contents', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_project_contents_content_type'), 'project_contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_project_contents_created_at'), 'project_contents', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_contents_episode_number'), 'project_contents', ['episode_number'], unique=False)
    op.create_index(op.f('ix_project_contents_is_locked'), 'project_contents', ['is_locked'], unique=False)
    op.create_index(op.f('ix_project_contents_project_id'), 'project_contents', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_contents_source_content_id'), 'project_contents', ['source_content_id'], unique=False)
    op.create_index(op.f('ix_project_contents_title'), 'project_contents', ['title'], unique=False)
    op.create_index(op.f('ix_project_contents_version'), 'project_contents', ['version'], unique=False)
    op.create_table('asset_representations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_version_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_representations_asset_version_id'), 'asset_representations', ['asset_version_id'], unique=False)
    op.create_table('project_asset_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['project_contents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['creative_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_asset_links_asset_id'), 'project_asset_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_project_asset_links_content_id'), 'project_asset_links', ['content_id'], unique=False)
    op.create_index(op.f('ix_project_asset_links_created_at'), 'project_asset_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_asset_links_project_id'), 'project_asset_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_asset_links_relation'), 'project_asset_links', ['relation'], unique=False)
    op.create_index(op.f('ix_project_asset_links_role'), 'project_asset_links', ['role'], unique=False)
    op.create_table('project_generation_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scene', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['project_contents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['creative_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_generation_logs_content_id'), 'project_generation_logs', ['content_id'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_created_at'), 'project_generation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_model'), 'project_generation_logs', ['model'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_project_id'), 'project_generation_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_provider'), 'project_generation_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_ref_id'), 'project_generation_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_scene'), 'project_generation_logs', ['scene'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_stage'), 'project_generation_logs', ['stage'], unique=False)
    op.create_index(op.f('ix_project_generation_logs_status'), 'project_generation_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_generation_logs_status'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_stage'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_scene'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_ref_id'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_provider'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_project_id'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_model'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_created_at'), table_name='project_generation_logs')
    op.drop_index(op.f('ix_project_generation_logs_content_id'), table_name='project_generation_logs')
    op.drop_table('project_generation_logs')
    op.drop_index(op.f('ix_project_asset_links_role'), table_name='project_asset_links')
    op.drop_index(op.f('ix_project_asset_links_relation'), table_name='project_asset_links')
    op.drop_index(op.f('ix_project_asset_links_project_id'), table_name='project_asset_links')
    op.drop_index(op.f('ix_project_asset_links_created_at'), table_name='project_asset_links')
    op.drop_index(op.f('ix_project_asset_links_content_id'), table_name='project_asset_links')
    op.drop_index(op.f('ix_project_asset_links_asset_id'), table_name='project_asset_links')
    op.drop_table('project_asset_links')
    op.drop_index(op.f('ix_asset_representations_asset_version_id'), table_name='asset_representations')
    op.drop_table('asset_representations')
    op.drop_index(op.f('ix_project_contents_version'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_title'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_source_content_id'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_project_id'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_is_locked'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_episode_number'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_created_at'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_content_type'), table_name='project_contents')
    op.drop_index(op.f('ix_project_contents_chapter_number'), table_name='project_contents')
    op.drop_table('project_contents')
    op.drop_index(op.f('ix_book_source_cookies_is_active'), table_name='book_source_cookies')
    op.drop_index(op.f('ix_book_source_cookies_expires_at'), table_name='book_source_cookies')
    op.drop_index(op.f('ix_book_source_cookies_domain'), table_name='book_source_cookies')
    op.drop_index(op.f('ix_book_source_cookies_book_source_id'), table_name='book_source_cookies')
    op.drop_table('book_source_cookies')
    op.drop_index(op.f('ix_asset_versions_version_number'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_created_at'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_asset_node_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_index(op.f('ix_asset_tag_links_tag_id'), table_name='asset_tag_links')
    op.drop_index(op.f('ix_asset_tag_links_asset_node_id'), table_name='asset_tag_links')
    op.drop_table('asset_tag_links')
    op.drop_index(op.f('ix_asset_relations_target_id'), table_name='asset_relations')
    op.drop_index(op.f('ix_asset_relations_source_id'), table_name='asset_relations')
    op.drop_index(op.f('ix_asset_relations_relation_type'), table_name='asset_relations')
    op.drop_table('asset_relations')
    op.drop_index(op.f('ix_asset_embeddings_asset_node_id'), table_name='asset_embeddings')
    op.drop_table('asset_embeddings')
    op.drop_index(op.f('ix_ai_models_model_type'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_file_hash'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_civitai_model_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_base_model'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_asset_node_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('agent_skills')
    op.drop_index(op.f('ix_agent_run_steps_tool_name'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_step_type'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_status'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_session_id'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_run_id'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_profile_id'), table_name='agent_run_steps')
    op.drop_index(op.f('ix_agent_run_steps_order_index'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index(op.f('ix_agent_messages_tool_call_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_thread_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_run_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_memory_snapshots_user_id'), table_name='agent_memory_snapshots')
    op.drop_index(op.f('ix_agent_memory_snapshots_session_id'), table_name='agent_memory_snapshots')
    op.drop_index(op.f('ix_agent_memory_snapshots_run_id'), table_name='agent_memory_snapshots')
    op.drop_index(op.f('ix_agent_memory_snapshots_profile_id'), table_name='agent_memory_snapshots')
    op.drop_table('agent_memory_snapshots')
    op.drop_index(op.f('ix_agent_memories_thread_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_run_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index(op.f('ix_agent_context_snapshots_thread_id'), table_name='agent_context_snapshots')
    op.drop_index(op.f('ix_agent_context_snapshots_run_id'), table_name='agent_context_snapshots')
    op.drop_index(op.f('ix_agent_context_snapshots_kind'), table_name='agent_context_snapshots')
    op.drop_index(op.f('ix_agent_context_snapshots_created_at'), table_name='agent_context_snapshots')
    op.drop_table('agent_context_snapshots')
    op.drop_table('wechat_mp_downloads')
    op.drop_index(op.f('ix_vector_indexes_name'), table_name='vector_indexes')
    op.drop_table('vector_indexes')
    op.drop_index(op.f('ix_vector_docs_asset_id'), table_name='vector_docs')
    op.drop_table('vector_docs')
    op.drop_index(op.f('ix_torrent_downloads_torrent_hash'), table_name='torrent_downloads')
    op.drop_index(op.f('ix_torrent_downloads_status'), table_name='torrent_downloads')
    op.drop_index(op.f('ix_torrent_downloads_engine'), table_name='torrent_downloads')
    op.drop_table('torrent_downloads')
    op.drop_index(op.f('ix_tags_path'), table_name='tags')
    op.drop_index(op.f('ix_tags_parent_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_level'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_index(op.f('ix_tags_asset_count'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_story_character_portraits_story_id'), table_name='story_character_portraits')
    op.drop_index(op.f('ix_story_character_portraits_character_name'), table_name='story_character_portraits')
    op.drop_table('story_character_portraits')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_platform_templates_template_stage'), table_name='platform_templates')
    op.drop_index(op.f('ix_platform_templates_template_scope'), table_name='platform_templates')
    op.drop_index(op.f('ix_platform_templates_platform'), table_name='platform_templates')
    op.drop_table('platform_templates')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_novel_chapters_chapter_index'), table_name='novel_chapters')
    op.drop_index(op.f('ix_novel_chapters_asset_id'), table_name='novel_chapters')
    op.drop_table('novel_chapters')
    op.drop_index(op.f('ix_live2d_motions_model_id'), table_name='live2d_motions')
    op.drop_table('live2d_motions')
    op.drop_index(op.f('ix_live2d_models_name'), table_name='live2d_models')
    op.drop_table('live2d_models')
    op.drop_index(op.f('ix_live2d_bones_model_id'), table_name='live2d_bones')
    op.drop_table('live2d_bones')
    op.drop_index(op.f('ix_creative_projects_title'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_status'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_source_type'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_project_type'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_current_stage'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_created_at'), table_name='creative_projects')
    op.drop_table('creative_projects')
    op.drop_index(op.f('ix_comfyui_workflow_templates_name'), table_name='comfyui_workflow_templates')
    op.drop_index(op.f('ix_comfyui_workflow_templates_category'), table_name='comfyui_workflow_templates')
    op.drop_table('comfyui_workflow_templates')
    op.drop_index(op.f('ix_comfyui_workflow_presets_template_id'), table_name='comfyui_workflow_presets')
    op.drop_index(op.f('ix_comfyui_workflow_presets_name'), table_name='comfyui_workflow_presets')
    op.drop_table('comfyui_workflow_presets')
    op.drop_index(op.f('ix_comfyui_tasks_template_id'), table_name='comfyui_tasks')
    op.drop_index(op.f('ix_comfyui_tasks_task_type'), table_name='comfyui_tasks')
    op.drop_index(op.f('ix_comfyui_tasks_status'), table_name='comfyui_tasks')
    op.drop_index(op.f('ix_comfyui_tasks_prompt_id'), table_name='comfyui_tasks')
    op.drop_table('comfyui_tasks')
    op.drop_index(op.f('ix_comfyui_nodes_name'), table_name='comfyui_nodes')
    op.drop_table('comfyui_nodes')
    op.drop_index(op.f('ix_characters_portrait_node_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_story_links_world_name'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_world_id'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_usage_role'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_story_id'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_local_status'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_local_faction'), table_name='character_story_links')
    op.drop_index(op.f('ix_character_story_links_character_id'), table_name='character_story_links')
    op.drop_table('character_story_links')
    op.drop_index(op.f('ix_book_sources_rule_format'), table_name='book_sources')
    op.drop_index(op.f('ix_book_sources_book_source_url'), table_name='book_sources')
    op.drop_index(op.f('ix_book_sources_book_source_name'), table_name='book_sources')
    op.drop_table('book_sources')
    op.drop_index(op.f('ix_asset_nodes_use_count'), table_name='asset_nodes')
    op.drop_index(op.f('ix_asset_nodes_phash'), table_name='asset_nodes')
    op.drop_index(op.f('ix_asset_nodes_parent_id'), table_name='asset_nodes')
    op.drop_index(op.f('ix_asset_nodes_name'), table_name='asset_nodes')
    op.drop_index(op.f('ix_asset_nodes_created_at'), table_name='asset_nodes')
    op.drop_index(op.f('ix_asset_nodes_asset_type'), table_name='asset_nodes')
    op.drop_table('asset_nodes')
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('ai_usage_logs')
    op.drop_table('ai_provider_metadata')
    op.drop_table('ai_connectors')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_agent_threads_user_id'), table_name='agent_threads')
    op.drop_index(op.f('ix_agent_threads_status'), table_name='agent_threads')
    op.drop_index(op.f('ix_agent_threads_active_profile_id'), table_name='agent_threads')
    op.drop_table('agent_threads')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_profile_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_profiles_user_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_role_type'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_name'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_is_default'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_is_builtin'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_default_project_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
